version: '3.9'

services:
  redis:
    image: redis:alpine
    networks:
      - app-network

  api:
    build: ./api/
    container_name: api
    env_file:
      - .env
    restart: always
    network_mode: host  # Use host network mode
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "172.17.112.242:9092"

  webhook:
    build: ./
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
